Repository HackAtUCI/irvinehacks-site-2024, pull requests merged in 2023-12, with the labels that each got.

#92 Implement guest authentication with passphrases
  apps/api/README.md
  apps/api/index.py
  apps/api/src/app.py
  apps/api/src/auth/guest_auth.py
  apps/api/src/routers/guest.py
  apps/api/tests/test_guest.py
  apps/api/tests/test_guest_auth.py
Labels: backend

#98 Add temporary unstyled Login and Guest Login forms
  apps/site/src/app/guest-login/GuestLogin.tsx
  apps/site/src/app/guest-login/components/VerificationForm.tsx
  apps/site/src/app/guest-login/page.tsx
  apps/site/src/app/login/Login.tsx
  apps/site/src/app/login/components/LoginForm.tsx
  apps/site/src/app/login/page.tsx
  apps/site/src/app/portal/Portal.tsx
  apps/site/src/app/portal/page.tsx
  apps/site/src/lib/components/ValidatingForm/ValidatingForm.tsx
Labels: enhancement

#113 Add `/user/apply` API endpoint to receive hacker applications
  apps/api/src/models/ApplicationData.py
  apps/api/src/routers/user.py
  apps/api/src/utils/email_handler.py
  apps/api/src/utils/resume_handler.py
  apps/api/src/utils/user_record.py
  apps/api/tests/test_user_apply.py
  apps/site/src/app/apply/sections/Form/AgeInformation.tsx
  apps/site/src/app/apply/sections/Form/ProfileInformation.tsx
  apps/site/src/app/apply/sections/Form/ResumeInformation.tsx
  apps/site/src/app/apply/sections/Form/SchoolInformation.tsx
Labels: enhancement, backend

#161 Update Sanity resource schema
  apps/sanity/schemas/faqs.ts
  apps/sanity/schemas/index.ts
  apps/sanity/schemas/resource.ts
  apps/sanity/schemas/resourceCategory.ts
Labels: sanity
